apiVersion: v1
kind: Service
metadata:
  name: {{.Values.zookeeper.client_service.name}}
  namespace: {{.Values.kafka.namespace.name}}
  labels:
    app: {{.Values.zookeeper.labels.name}}
spec:
  selector:
    app: {{.Values.zookeeper.labels.name}}
  ports:
    - name: client
      port: {{.Values.zookeeper.port.client}}
      targetPort: {{.Values.zookeeper.port.client}}
  type: LoadBalancer # (ClusterIP or LoadBalancer)