apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.kafka.configmap.name}}
  namespace: {{.Values.kafka.namespace.name}}
data:
  server.properties: |
    {{- include "kafka.configmap" . | nindent 4}}